README and .bat files added
pelageech/BDUTS pull request #42
Opened 2023-03-08 10:09 UTC by K4rsion

2023-03-08 10:13 UTC, pelageech requested changes

2023-03-08 10:13 UTC, pelageech commented on start_server.bat
> +cd "..\locallibrary\"
Стоит сделать без переходов по папкам

2023-03-08 13:44 UTC, peyuaa commented
.bat файлы же только для винды работают, мне кажется нам надо перейти к докерконтейнерам, чтобы у нас все это запускалось у всех одинаково

2023-03-08 13:56 UTC, pelageech commented
@peyuaa а ты предлагаешь сразу что ли перейти к ним?
Идея хорошая, но стоит ли щас этим заниматься? Пока что .sh можешь для себя создать что ли

2023-03-13 04:09 UTC, pelageech commented
@K4rsion удали .bat файл, чтобы я замерджил, он не нужен
А readme оставь

2023-03-13 04:35 UTC, K4rsion commented
@pelageech все сделал

2023-03-13 04:36 UTC, pelageech approved these changes

2023-03-13 04:36 UTC, merged