json made
pelageech/BDUTS pull request #71
Opened 2023-05-01 06:19 UTC by pelageech

2023-05-09 08:52 UTC, peyuaa requested changes

2023-05-09 08:52 UTC, peyuaa commented on lb/loadBalancer.go
> +		type AddForm struct {
Почему бы эту структуру не объявить вне функции? Чтобы она была публичной

2023-05-09 08:52 UTC, peyuaa commented on lb/loadBalancer.go
> +		url := add.Url
Зачем создавать новую переменную? Можно передать в функцию сразу add.Url

2023-05-09 08:52 UTC, peyuaa commented on lb/loadBalancer.go
> +		type RemoveForm struct {
Аналогично предлагаю вынести структуры куда-нибудь наверх, а не объявлять в функции.

2023-05-09 08:52 UTC, peyuaa commented on lb/loadBalancer.go
> +		url := rem.Url
Аналогично предлагаю передавать в функцию сразу rem.Url

2023-05-09 09:41 UTC, peyuaa commented
+ README переделать, если там не так, как здесь

2023-05-09 10:05 UTC, pelageech commented
Эти реквесты как раз соответствуют readme

2023-05-12 10:10 UTC, peyuaa requested changes

2023-05-12 10:10 UTC, peyuaa commented on lb/adminHandlers.go
>  	"github.com/pelageech/BDUTS/config"
проблему с порядком импортов вижу я

2023-05-12 10:10 UTC, peyuaa commented on lb/adminHandlers.go
> +type AddForm struct {
Вообще по конвенции ко всем экспортируемым функциями/структурам (которые с большой буквы) рекомендуется писать комментарии, поэтому можешь их добавить

2023-05-12 10:10 UTC, peyuaa commented on lb/adminHandlers.go
> +type RemoveForm struct {
И сюда комментарий

2023-05-12 10:10 UTC, peyuaa commented on lb/adminHandlers.go
>  func (lb *LoadBalancer) AddServer(rw http.ResponseWriter, req *http.Request) {
Комментарий

2023-05-12 10:10 UTC, peyuaa commented on lb/adminHandlers.go
>  func (lb *LoadBalancer) RemoveServer(rw http.ResponseWriter, req *http.Request) {
Комментарий

2023-05-12 10:10 UTC, peyuaa commented on lb/adminHandlers.go
> +			fmt.Sprintf("<tr>"+
мне все еще кажется что фронт сам должен эт отрисовывать, а мы просто возвращать массив серверов, но наверное надо будет с Кириллом обсудить

2023-05-12 10:59 UTC, pelageech commented on lb/adminHandlers.go
>  	"github.com/pelageech/BDUTS/config"
обоже

2023-05-12 13:14 UTC, merged