An application for administrating a balancer with terminal
pelageech/BDUTS pull request #83
Opened 2023-05-13 06:03 UTC by pelageech

2023-05-13 08:05 UTC, pelageech commented on admin_app/main.go
> +	tr = &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}} // todo: configure tls in right way
хз как пофиксить это, сую ему сертификат - а никак

2023-05-13 16:00 UTC, peyuaa requested changes

2023-05-13 16:00 UTC, peyuaa commented on admin_app/main.go
> +	tr = &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}} // todo: configure tls in right way
Ну это надо будет пофиксить перед мерджем

2023-05-13 16:00 UTC, peyuaa commented on admin_app/main.go
> +type AddRequestBodyJSON struct {
Комментарии

2023-05-13 16:00 UTC, peyuaa commented on admin_app/main.go
> +type AddRequestBodyJSON struct {
Или сделать приватной

2023-05-13 16:00 UTC, peyuaa commented on admin_app/main.go
> +type RemoveRequestBodyJSON struct {
Комментарии или приватной

2023-05-13 16:00 UTC, peyuaa commented on admin_app/main.go
> +	if *host == "" {
host никогда не будет равен "", он же по умолчанию инициализируется как локалхост?

2023-05-13 16:00 UTC, peyuaa commented on admin_app/main.go
> +		flag.Usage()
Добавь какую-то инструкцию как пользовать, потому что я попытался в консоли позапускать. Неочевидно как это использовать.

2023-05-13 16:00 UTC, peyuaa commented on admin_app/main.go
> +	r := strings.NewReader(string(body))
Есть bytes.NewReader.
https://pkg.go.dev/bytes#NewReader

Ненужные преобразования одного типа в другой

2023-05-13 16:00 UTC, peyuaa commented on admin_app/main.go
> +	r := strings.NewReader(string(body))
аналогично лишние преобразования одного типа в другой

2023-05-13 16:00 UTC, peyuaa commented on admin_app/main.go
> +	if *remove != defaultUrl {
А что в одном запросе мы можем и добавлять, и удалять одновременно -- это так и задумано?

2023-05-14 02:20 UTC, pelageech commented on admin_app/main.go
> +	if *remove != defaultUrl {
ну кто хочет - пусть так делает, они, во-первых, никак не конфликтуют, и, во-вторых, исполнятся последовательно.

2023-05-14 02:27 UTC, pelageech commented on admin_app/main.go
> +		flag.Usage()
всмысле -help добавить?

2023-05-17 01:26 UTC, merged